accelerate launch --config_file ./config.yaml run.py \
    --split_dir ./data_split \
    --model TFTransUNet1D \
    --batch_size 32 \
    --epochs 100 \
    --lr 1e-3 \
    --regularizer 1e-5 \
    --betas 0.9 0.99 \
    --patience 10 \
    --save_checkpoint ./checkpoints/best_tftransunet1d.pth \
    --load_checkpoint ./checkpoints/best_tftransunet1d.pth \
    --mode train \
